/* AUTO-GENERATED by Apps Script GitHub publish */

window.TACT_EVENT_FEED = [
  {
    "slug": "2026-demo-past-event",
    "title": "Demo Past Event (Sample)",
    "date": "2026-01-12",
    "time": "2:00 PM - 4:00 PM",
    "location": "Hubballi",
    "status": "completed",
    "folder": "content/events/2026-demo-past-event",
    "pageUrl": "events/12-01-2026-demo-past-event-sample.html",
    "poster": "content/events/2026-demo-past-event/poster.svg",
    "teaser": "Sample past event added for previewing the homepage past-events card layout.",
    "homepageMatter": "This is a demo entry with a lightweight placeholder poster so you can verify how two past event cards look."
  },
  {
    "slug": "2026-nataka-community-stage",
    "title": "Vijnana Nataka Community Performance",
    "date": "2026-02-18",
    "time": "5:00 PM - 7:00 PM",
    "location": "Tumakuru",
    "status": "completed",
    "folder": "content/events/2026-nataka-community-stage",
    "pageUrl": "events/18-02-2026-vijnana-nataka-community-performance.html",
    "poster": "content/events/2026-nataka-community-stage/poster.jpg",
    "teaser": "Science theatre performance followed by open audience discussion.",
    "homepageMatter": "A community evening of science storytelling through theatre, music, and open audience conversation."
  },
  {
    "slug": "2026-harate-pu-college",
    "title": "Vijnana Harate at Government PU College",
    "date": "2026-03-22",
    "time": "10:30 AM - 1:00 PM",
    "location": "Bengaluru",
    "status": "scheduled",
    "folder": "content/events/2026-harate-pu-college",
    "pageUrl": "events/22-03-2026-vijnana-harate-at-government-pu-college.html",
    "poster": "content/events/2026-harate-pu-college/poster.jpg",
    "teaser": "Interactive science conversations and simple experiment stations for students and teachers.",
    "homepageMatter": "Join us for a high-energy Harate session with scientists and educators. Students will explore hands-on demos and open Q&A circles."
  },
  {
    "slug": "2026-03-26-hi-hihihihihhi",
    "title": "hi hihihihihhi",
    "date": "2026-03-26",
    "time": "10:00 AM - 1:00 PM",
    "location": "rayachoty",
    "status": "scheduled",
    "folder": "content/events/2026-03-26-hi-hihihihihhi",
    "pageUrl": "events/2026-03-26-hi-hihihihihhi.html",
    "poster": "content/events/2026-03-26-hi-hihihihihhi/poster.png",
    "teaser": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "homepageMatter": "hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi"
  },
  {
    "slug": "2026-03-28-hi-nitish",
    "title": "hi nitish",
    "date": "2026-03-28",
    "time": "10:00 AM - 1:00 PM",
    "location": "bandar",
    "status": "scheduled",
    "folder": "content/events/2026-03-28-hi-nitish",
    "pageUrl": "events/2026-03-28-hi-nitish.html",
    "poster": "content/events/2026-03-28-hi-nitish/poster.jpg",
    "teaser": "nithish",
    "homepageMatter": "nithish"
  },
  {
    "slug": "2026-03-29-hi-hihihihihhi",
    "title": "hi hihihihihhi",
    "date": "2026-03-29",
    "time": "6:00 AM - 6:30 AM",
    "location": "hyd",
    "status": "scheduled",
    "folder": "content/events/2026-03-29-hi-hihihihihhi",
    "pageUrl": "events/2026-03-29-hi-hihihihihhi.html",
    "poster": "content/events/2026-03-29-hi-hihihihihhi/poster.jpg",
    "teaser": "",
    "homepageMatter": "Use the same PIN-protected panel to publish events or add gallery collections without manual code edits.\nUse the same PIN-protected panel to publish events or add gallery collections without manual code edits.Use the same PIN-protected panel to publish events or add gallery collections without manual code edits."
  },
  {
    "slug": "2026-yuvati-mentorship-day",
    "title": "Vijnana Yuvati Mentorship Day",
    "date": "2026-04-10",
    "time": "9:30 AM - 4:00 PM",
    "location": "Mysuru",
    "status": "scheduled",
    "folder": "content/events/2026-yuvati-mentorship-day",
    "pageUrl": "events/10-04-2026-vijnana-yuvati-mentorship-day.html",
    "poster": "content/events/2026-yuvati-mentorship-day/poster.jpg",
    "teaser": "Mentor circles, scholarship clinic, and practical sessions on STEM pathways.",
    "homepageMatter": "A full-day programme focused on young women in STEM, with mentor hours, application guidance, and practical skilling workshops."
  }
];
