param(
  [Parameter(Mandatory = $true)]
  [ValidateSet("init-event", "normalize-photos", "build-feed", "validate")]
  [string]$Action,

  [string]$Slug,
  [string]$Title,
  [string]$Date,
  [string]$Time,
  [string]$Location,
  [string]$Root = "content/events"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function To-PosixPath([string]$Path) {
  return ($Path -replace "\\", "/")
}

function Get-EventDirs([string]$EventsRoot) {
  return Get-ChildItem $EventsRoot -Directory |
    Where-Object { $_.Name -notmatch "^_" } |
    Sort-Object Name
}

function Ensure-EventScaffold([string]$EventDir) {
  New-Item -ItemType Directory -Path $EventDir -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $EventDir "gallery") -Force | Out-Null
  New-Item -ItemType Directory -Path (Join-Path $EventDir "raw") -Force | Out-Null

  $pre = Join-Path $EventDir "pre-event.txt"
  $post = Join-Path $EventDir "post-event.md"
  if (-not (Test-Path $pre)) { Set-Content -Path $pre -Value "Short pre-event note." }
  if (-not (Test-Path $post)) {
    Set-Content -Path $post -Value "# Post Event Notes`n`n- Speakers:`n- Highlights:`n- Attendance:`n- Outcomes:`n"
  }
}

function Normalize-EventPhotos([string]$EventDir, [string]$EventSlug) {
  $imagePattern = @("*.jpg", "*.jpeg", "*.png", "*.webp", "*.svg")
  $galleryDir = Join-Path $EventDir "gallery"
  $rawDir = Join-Path $EventDir "raw"
  New-Item -ItemType Directory -Path $galleryDir -Force | Out-Null
  New-Item -ItemType Directory -Path $rawDir -Force | Out-Null

  # Move root-level photos (except poster) into raw first
  foreach ($pat in $imagePattern) {
    Get-ChildItem $EventDir -File -Filter $pat | Where-Object { $_.BaseName -ne "poster" } | ForEach-Object {
      Move-Item $_.FullName (Join-Path $rawDir $_.Name) -Force
    }
  }

  # If poster missing, promote first raw image to poster.jpg/.png/etc
  $poster = Get-ChildItem $EventDir -File | Where-Object { $_.BaseName -eq "poster" } | Select-Object -First 1
  if (-not $poster) {
    $firstRaw = Get-ChildItem $rawDir -File | Select-Object -First 1
    if ($firstRaw) {
      $posterName = "poster" + $firstRaw.Extension.ToLower()
      Move-Item $firstRaw.FullName (Join-Path $EventDir $posterName) -Force
    }
  }

  # Move remaining raw images into gallery with consistent names
  $counter = 1
  Get-ChildItem $galleryDir -File | ForEach-Object {
    $counter = $counter + 1
  }
  Get-ChildItem $rawDir -File | Sort-Object LastWriteTime, Name | ForEach-Object {
    $num = "{0:D3}" -f $counter
    $newName = "$EventSlug-$num$($_.Extension.ToLower())"
    Move-Item $_.FullName (Join-Path $galleryDir $newName) -Force
    $counter = $counter + 1
  }
}

function Build-Feed([string]$EventsRoot) {
  $feed = @()
  foreach ($dir in Get-EventDirs $EventsRoot) {
    $metaPath = Join-Path $dir.FullName "event.json"
    if (-not (Test-Path $metaPath)) { continue }
    $meta = Get-Content $metaPath -Raw | ConvertFrom-Json
    if (-not $meta.slug -or -not $meta.title -or -not $meta.date) { continue }

    $poster = Get-ChildItem $dir.FullName -File | Where-Object { $_.BaseName -eq "poster" } | Select-Object -First 1
    if (-not $poster) {
      $poster = Get-ChildItem (Join-Path $dir.FullName "gallery") -File | Select-Object -First 1
    }
    if (-not $poster) { continue }

    $entry = [ordered]@{
      slug = [string]$meta.slug
      title = [string]$meta.title
      date = [string]$meta.date
      time = [string]$meta.time
      location = [string]$meta.location
      status = [string]$meta.status
      folder = To-PosixPath((Join-Path $EventsRoot $dir.Name))
      poster = To-PosixPath((Join-Path (Join-Path $EventsRoot $dir.Name) $poster.Name))
      teaser = [string]$meta.teaser
      homepageMatter = [string]$meta.homepageMatter
    }
    $feed += [pscustomobject]$entry
  }

  # Keep ascending by event date for stable upcoming rotation
  $feed = $feed | Sort-Object date
  $json = $feed | ConvertTo-Json -Depth 4
  $out = @(
    "/* AUTO-GENERATED by tools/event-system.ps1 build-feed */",
    "",
    "window.TACT_EVENT_FEED = $json;"
  ) -join "`n"
  Set-Content -Path (Join-Path $EventsRoot "events-feed.js") -Value $out -Encoding utf8
}

switch ($Action) {
  "init-event" {
    if (-not $Slug -or -not $Title -or -not $Date -or -not $Time -or -not $Location) {
      throw "init-event requires -Slug -Title -Date -Time -Location"
    }
    $eventDir = Join-Path $Root $Slug
    Ensure-EventScaffold $eventDir
    $metaPath = Join-Path $eventDir "event.json"
    if (-not (Test-Path $metaPath)) {
      $meta = [ordered]@{
        slug = $Slug
        title = $Title
        date = $Date
        time = $Time
        location = $Location
        teaser = "One-line summary."
        homepageMatter = "Two to three lines for homepage."
        status = "scheduled"
      } | ConvertTo-Json -Depth 4
      Set-Content -Path $metaPath -Value $meta -Encoding utf8
    }
    Write-Host "Created event folder: $eventDir"
  }
  "normalize-photos" {
    if ($Slug) {
      $eventDir = Join-Path $Root $Slug
      if (-not (Test-Path $eventDir)) { throw "Event folder not found: $eventDir" }
      Normalize-EventPhotos $eventDir $Slug
      Write-Host "Normalized photos in $eventDir"
    } else {
      foreach ($dir in Get-EventDirs $Root) {
        Normalize-EventPhotos $dir.FullName $dir.Name
        Write-Host "Normalized photos in $($dir.Name)"
      }
    }
  }
  "build-feed" {
    Build-Feed $Root
    Write-Host "Generated $Root/events-feed.js"
  }
  "validate" {
    foreach ($dir in Get-EventDirs $Root) {
      $metaPath = Join-Path $dir.FullName "event.json"
      if (-not (Test-Path $metaPath)) {
        Write-Host "Missing event.json: $($dir.Name)"
      }
      if (-not (Get-ChildItem $dir.FullName -File | Where-Object { $_.BaseName -eq "poster" } | Select-Object -First 1)) {
        Write-Host "Missing poster.*: $($dir.Name)"
      }
    }
    Write-Host "Validation complete."
  }
}
